/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.java.programa;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        
        // encontrar el numero mayor

        System.out.println("Ingrese el primer numero: ");
        int n1 = sc.nextInt();

        System.out.println("Ingrese el segundo numero: ");
        int n2 = sc.nextInt();

        System.out.println("Ingrese el tercer numero: ");
        int n3 = sc.nextInt();

        if (n1 > n2 && n1 > n3) {

            System.out.println("El numero mayor es: " + n1);

        } else if (n2 > n1 && n2 > n3) {

            System.out.println("El numero mayor es: " + n2);

        } else {

            System.out.println("El numero mayor es: " + n3);

        } 
        if (n1==n2 && n2==n3){
            System.out.println("todos los numeros son iguales...");
        }
    }
}
